server:
  port: 8120

spring:
  profiles:
    active: dev
  application:
    name: service-sms  # 服务名

  redis:
    host: 127.0.0.1
    port: 6379
    password: wxiang
    database: 0
    timeout: 3000ms  # 最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  # 最大连接数，负值表示没有限制，默认为8
        max-wait: -1    # 最大阻塞等待时间，负值表示没有限制，默认-1
        max-idle: 8     # 最大空闲连接数，默认8
        min-idle: 0     # 最小空闲连接数，默认0

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

# 自定义的 阿里云短信 配置
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI5tAt22S8aAAwWP3Vr7Fv
    key-secret: f7ekxayd3XFIak81TFWlgQgJfRukTs
    template-code: SMS-96695065
    sign-name: 谷粒

# openfeign默认的连接超时时间为1秒，测试时很可能会出现远程调用超时错误
feign:
  client:
    config:
      default:
        connectTimeout: 10000  # 连接超时配置
        readTimeout: 60000 # 执行超时配置
  # 开启Feign对Sentinel的支持，即开启服务熔断功能
  sentinel:
    enabled: true


logging:
  level:
    com.wxiang.srb.sms.client.CoreUserInfoClient: DEBUG   # 以什么级别监控哪个接口
